- hosts: deploy
  tasks:

    - name: Ensure Ubuntu deployment container exists
      community.docker.docker_container:
        name: ubuntu-deploy
        image: ubuntu:22.04
        state: started
        detach : true
        command: tail -f /dev/null
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    - name: Install Docker inside deployment container
      command: >
        docker exec ubuntu-deploy bash -c
        "apt update && apt install -y docker.io"

    - name: Pull calculator image from Docker Hub
      command: >
        docker exec ubuntu-deploy docker pull venerableharsha/calculator-app:latest

    - name: Run calculator container inside deployment container
      command: >
        docker exec ubuntu-deploy
        docker run -dit --name calculator-container venerableharsha/calculator-app:latest